# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "BestSwiftRepo.xcworkspace", scheme: "BestSwiftRepo")
  end

  lane :tests do
    run_tests(workspace: "BestSwiftRepo.xcworkspace",
            scheme: "BestSwiftRepo")  
  end

  desc "Create ipa"
  lane :build do
    enable_automatic_code_signing
    increment_build_number
    gym
  end

  lane :beta do
    build_app(scheme: "BestSwiftRepo")
  end
end
